<?php

return [
	// Examples from README.md
	[
		'input' => 'test',
		'containsEmoji' => false,
		'onlyEmoji ignoreWhitespace=true' => false,
		'onlyEmoji ignoreWhitespace=false' => false,
		'removeEmoji' => 'test',
		'startingEmojis ignoreWhitespace=true' => [],
		'startingEmojis ignoreWhitespace=false' => [],
	],
	[
		'input' => 'test 👍',
		'containsEmoji' => true,
		'onlyEmoji ignoreWhitespace=true' => false,
		'onlyEmoji ignoreWhitespace=false' => false,
		'removeEmoji' => 'test ',
		'startingEmojis ignoreWhitespace=true' => [],
		'startingEmojis ignoreWhitespace=false' => [],
	],
	[
		'input' => '👍😘',
		'containsEmoji' => true,
		'onlyEmoji ignoreWhitespace=true' => true,
		'onlyEmoji ignoreWhitespace=false' => true,
		'removeEmoji' => '',
		'startingEmojis ignoreWhitespace=true' => ['👍', '😘'],
		'startingEmojis ignoreWhitespace=false' => ['👍', '😘'],
	],
	[
		'input' => '👍 😘',
		'containsEmoji' => true,
		'onlyEmoji ignoreWhitespace=true' => true,
		'onlyEmoji ignoreWhitespace=false' => false,
		'removeEmoji' => ' ',
		'startingEmojis ignoreWhitespace=true' => ['👍', '😘'],
		'startingEmojis ignoreWhitespace=false' => ['👍'],
	],
	[
		'input' => '👍😘 test',
		'containsEmoji' => true,
		'onlyEmoji ignoreWhitespace=true' => false,
		'onlyEmoji ignoreWhitespace=false' => false,
		'removeEmoji' => ' test',
		'startingEmojis ignoreWhitespace=true' => ['👍', '😘'],
		'startingEmojis ignoreWhitespace=false' => ['👍', '😘'],
	],
	[
		'input' => '👍 😘 test',
		'containsEmoji' => true,
		'onlyEmoji ignoreWhitespace=true' => false,
		'onlyEmoji ignoreWhitespace=false' => false,
		'removeEmoji' => '  test',
		'startingEmojis ignoreWhitespace=true' => ['👍', '😘'],
		'startingEmojis ignoreWhitespace=false' => ['👍'],
	],
	// Other tests
	[
		'input' => 'тест1 👍 👍 тест2',
		'containsEmoji' => true,
		'onlyEmoji ignoreWhitespace=true' => false,
		'onlyEmoji ignoreWhitespace=false' => false,
		'removeEmoji' => 'тест1   тест2',
		'startingEmojis ignoreWhitespace=true' => [],
		'startingEmojis ignoreWhitespace=false' => [],
	],
	[
		'input' => '👍 👍 👍 тест',
		'containsEmoji' => true,
		'onlyEmoji ignoreWhitespace=true' => false,
		'onlyEmoji ignoreWhitespace=false' => false,
		'removeEmoji' => '   тест',
		'startingEmojis ignoreWhitespace=true' => ['👍', '👍', '👍'],
		'startingEmojis ignoreWhitespace=false' => ['👍'],
	],
	[
		'input' => '👍👍👍тест',
		'containsEmoji' => true,
		'onlyEmoji ignoreWhitespace=true' => false,
		'onlyEmoji ignoreWhitespace=false' => false,
		'removeEmoji' => 'тест',
		'startingEmojis ignoreWhitespace=true' => ['👍', '👍', '👍'],
		'startingEmojis ignoreWhitespace=false' => ['👍', '👍', '👍'],
	],
	[
		'input' => '😘 😎 🤩',
		'containsEmoji' => true,
		'onlyEmoji ignoreWhitespace=true' => true,
		'onlyEmoji ignoreWhitespace=false' => false,
		'removeEmoji' => '  ',
		'startingEmojis ignoreWhitespace=true' => ['😘', '😎', '🤩'],
		'startingEmojis ignoreWhitespace=false' => ['😘'],
	],
	[
		'input' => '😘😎🤩',
		'containsEmoji' => true,
		'onlyEmoji ignoreWhitespace=true' => true,
		'onlyEmoji ignoreWhitespace=false' => true,
		'removeEmoji' => '',
		'startingEmojis ignoreWhitespace=true' => ['😘', '😎', '🤩'],
		'startingEmojis ignoreWhitespace=false' => ['😘', '😎', '🤩'],
	],
	[
		'input' => '😘😎 🤩',
		'containsEmoji' => true,
		'onlyEmoji ignoreWhitespace=true' => true,
		'onlyEmoji ignoreWhitespace=false' => false,
		'removeEmoji' => ' ',
		'startingEmojis ignoreWhitespace=true' => ['😘', '😎', '🤩'],
		'startingEmojis ignoreWhitespace=false' => ['😘', '😎'],
	],
	[
		'input' => 'тест test',
		'containsEmoji' => false,
		'onlyEmoji ignoreWhitespace=true' => false,
		'onlyEmoji ignoreWhitespace=false' => false,
		'removeEmoji' => 'тест test',
		'startingEmojis ignoreWhitespace=true' => [],
		'startingEmojis ignoreWhitespace=false' => [],
	],
];
